# Initial idea of repoman checks: https://github.com/mrueg/repoman-travis

# use "Trusty" as "Precise" has bash 4.2 only, which doesn't support nameref vars
sudo: required
dist: trusty
language: python
python:
    - "3.4" # repoman seems to be fastest with python-3.4
addons:
    apt:
        sources:
            - debian-sid
        packages:
            - shellcheck

git:
    depth: 1
branches:
    only:
        - master
        - dev
        - /^ci\//

## env config and env-based matrix
env:
    global:
        ## configurable variables
        - OVERLAY_NAME='rindeal'
    matrix:
        - PORTAGE_VER="2.3.0" REPOMAN_VER="2.3.0"
        - SHELLCHECK=1
## final touches to the matrix
matrix:
    fast_finish: true
    allow_failures:
            - env: SHELLCHECK=1

cache:
    pip: true
    directories:
        - ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/
before_cache:
    - rm -v -f ${HOME}/.cache/pip/log/debug.log

# -----------------------------------------------------------------------------

before_install:
    - source .travis/setup_environment.sh

install:
    - .travis/run_install.sh

script:
    - .travis/run_tests.sh

# after_success:
#     - cd "${TRAVIS_BUILD_DIR}"
#     - .travis/setup_git.sh

# -----------------------------------------------------------------------------

notifications:
  email: false
  hipchat:
    rooms:
      secure: qFt4CiPYVtqWLZQxOcNJd5dbYEyrImEAsDFjqz8PWt5P+xNFwte+09kYXPauEuUOCSnZjeRB2x6ngTD7r+WqJc4Cs5zQhfe3c/cptdyKFA252Tpo3UNRE69rieDlt3Chrq7jUAucrDkzeu/zrKFvwpKq0az12CfW7HxUgy2jBoikIBIRnAAkdG8DO6bNzveNsRt8pBbnGt80KZAQhRS5DwsNtzpiJrXcj6AkFls0sDxvWVB1rZC6qZ5xB0DGTH9Esa+a+Au+SwjnK4C+GqeeiYgD9nVWQ4rvyCuyfcUqEcts8jOE2zxK475EpWutpVEkMWGfLNEmllElhyjay+QemacACYC2izI8DRaXck29qK2Hr4pNkWR1b5pEwdkS5tHWhnd+/hkKXagMYYclJ0w7X/vzyBkKyre1SLkYA6iyzv/AREuq7Ievk3bRY+e40+1tUgUWHaykOuwSYKOe2LwHpMfX3VMOiiyEvCcVf69TVjftyGU7YELABm8buGYdaVldSQcZq7mOX4Ddqo5bKOwgexpG/pWSbRDUUiV6lb88s2OiRpZqxN9gW3x5o7C3tEwp6SaNJZ3PL86c5isiIFbhtq8hCzgEfH8ISb/MSHpLD2RkQruUtsTKt8sJ51wUVj7wZp1Zi+33CLVasO6sx115EXV55ub30Z8pZzDwZwlRuQU=
    notify: true
